channels:
  - conda-forge

dependencies:
  - python=3.10
  - jupyterlab
  - jupyter_server
  - pip

  # R stack
  - r-base=4.3
  - r-tidyverse
  - r-irkernel
  - r-raster
  - r-sf
  - r-rnaturalearth
  - r-maxnet
  - r-remotes

  # optional but useful
  - git
